export const HOME_SCREEN = 'HOME_SCREEN';
export const DETAIL_SCREEN = 'DETAIL_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN';
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const SHOP_SCREEN = 'SHOP_SCREEN';
export const STACK_NAVIGATOR_AUTHENTICATION = 'STACK_NAVIGATOR_AUTHENTICATION';
export const BOTTOM_TAB_NAVIGATOR = 'BOTTOM_TAB_NAVIGATOR';
